# Generated by Django 6.0 on 2025-12-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='نام و نام خانوادگی')),
                ('phone', models.EmailField(max_length=255, unique=True, verbose_name='تلفن همراه')),
                ('text', models.TextField(max_length=5000, verbose_name='متن پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_red', models.BooleanField(default=False, verbose_name='خوانده شده / خوانده نشده')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط با ما',
            },
        ),
    ]
